server:
  port: 15597

gpt:
  SK: 
  AK: 

spring:
  thymeleaf:
    cache: true
    servlet:
      content-type: application/json
    encoding: UTF-8
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/your_db?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris: http://localhost:9200
    password: 
    username: 
